---
swagger: 2.0
basePath: /Prod
info:
  title: "deploiement-java-api"
schemes:
- https
paths:
  "/":
    x-amazon-apigateway-any-method:
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${deploiementJavaFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws
definitions:
  Empty:
    type: object
    title: Empty Schema
